### ISSUE TITLE
Вопрос по игровому времени

### ISSUE THREAD

**Issue by PavelZubkov** [perfectdaemon/ts-game#30]
https://github.com/perfectdaemon/ts-game/blob/d3b90c8291ae39dd2730733e97538ae3ffde7b41/app/engine/game-base.ts#L33

```
const gameLoop = (timestamp: number) => {
      this.lastTime = this.currentTime;
      this.currentTime = timestamp / 1000;

      this.deltaTime = Math.min(this.currentTime - this.lastTime, 0.1);

      if (!this.pauseAll) {
        this.onUpdate(this.deltaTime);
        this.onRender();
      }

      window.requestAnimationFrame(gameLoop);

    };
```

Добрый день.

Функция передаваемая в requestAnimationFrame, при вызове получает единственный параметр `requestId: number`. Он используется для отмены анимации, по аналогии с таймаутами `clearTimeout(timerId)`.

Если запускать в консоле, видно что requestId при каждом запуске увеличивается на единицу.

Есть ли какая-нибудь разница между использованием `requestId` в качестве `timetamp` и к примеру `perfomance.now()`? Смущает, что `requestId` привязан к количеству вызовов колбека, а не к реальному времени

**Comment by perfectdaemon** [comment]
Привет!

Если честно, я не помню, почему я выбрал такое решение, а не performance.now(). Скорее всего где-то подсмотрел, и везде считалось, что в gameLoop передается текущее время. 

Если это не так и в gameLoop передается просто некий инкрементный id, то это баг, и надо переходить на performance.now() или аналогичные счетчики.

Я постараюсь поисследовать это в свободное время

**Comment by PavelZubkov** [comment]
Да, где-то видел в примере, что `requestId` timestamp'ом называли, спасибо за ответ
